package adapter_test

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"testing"

	"github.com/docker/docker/api/types/container"
	"github.com/docker/docker/api/types/network"
	"github.com/docker/docker/client"
	hdmodule "github.com/nodeset-org/hyperdrive-ethereum/adapter/hd-module"
	internal_test "github.com/nodeset-org/hyperdrive-ethereum/internal/test"
	"github.com/nodeset-org/hyperdrive-ethereum/shared/utils/command"
)

var (
	// Adapter client for global mode
	// gac *hdmodule.AdapterClient

	// Adapter client for project mode
	pac *hdmodule.AdapterClient

	// Docker client
	docker *client.Client

	// Info for the example module
	// modInfo *hdconfig.ModuleInfo
)

func TestMain(m *testing.M) {
	var err error
	docker, err = client.NewClientWithOpts(client.WithAPIVersionNegotiation())
	if err != nil {
		fail(fmt.Errorf("error creating Docker client: %w", err))
	}

	// Check if the adapter container is running
	projectAdapterID := getContainerID("hyperdrive-ethereum-project-adapter")
	if projectAdapterID == "" {
		fmt.Println("Project adapter not found. Starting it...")

		// Run the container
		runCmd := fmt.Sprintf(
			"docker run --rm -d "+
				"-e HD_ADAPTER_MODE=project "+
				"-e HD_PROJECT_NAME=hyperdrive-test "+
				"-e HD_CONFIG_DIR=/app/config "+
				"-e HD_LOG_DIR=/app/logs "+
				"-e HD_KEY_FILE=/app/secret/key "+
				"-v %s:/app/config "+
				"-v %s:/app/logs "+
				"-v %s:/app/secret "+
				"--network hyperdrive-test_net "+
				"--name hyperdrive-ethereum-project-adapter "+
				"hyperdrive-ethereum:latest",
			"./config", "./logs", "./secret",
		)
		fmt.Printf("!!runCmd: %v\n", runCmd)
		_, err := command.ReadOutput(runCmd)
		if err != nil {
			fail(fmt.Errorf("error starting project adapter container: %w", err))
		}

		// Verify it's running now
		projectAdapterID = getContainerID("hyperdrive-ethereum-project-adapter")
		if projectAdapterID == "" {
			fail(fmt.Errorf("failed to start project adapter container"))
		}
	}

	// Now that it's running, initialize the adapter client
	pac, err = hdmodule.NewAdapterClient("hyperdrive-ethereum-project-adapter", "test-key")
	if err != nil {
		fail(fmt.Errorf("error creating project adapter client: %w", err))
	}

	// Run tests
	code := m.Run()
	cleanup()
	os.Exit(code)
}

// Get the ID of the container with the given name
func getContainerID(name string) string {
	containerList, err := docker.ContainerList(context.Background(), container.ListOptions{
		All: true,
	})
	fmt.Printf("!!containerList: %v\n", containerList)
	if err != nil {
		fail(fmt.Errorf("error inspecting adapter container: %w", err))
	}
	for _, container := range containerList {
		for _, containerName := range container.Names {
			if containerName == "/"+name {
				return container.ID
			}
		}
	}
	return ""
}

// Create the Docker container and initialize the adapter client
func initializeArtifacts() {
	// Make the dirs
	if err := os.MkdirAll(internal_test.LogDir, 0755); err != nil {
		fail(fmt.Errorf("error creating log dir: %w", err))
	}
	if err := os.MkdirAll(internal_test.CfgDir, 0755); err != nil {
		fail(fmt.Errorf("error creating config dir: %w", err))
	}
	if err := os.MkdirAll(filepath.Dir(internal_test.KeyPath), 0755); err != nil {
		fail(fmt.Errorf("error creating secrets dir: %w", err))
	}

	// Create the key file, or get the key if it already exists
	err := os.WriteFile(internal_test.KeyPath, []byte(internal_test.TestKey), 0644)
	if err != nil {
		fail(fmt.Errorf("error creating key file: %w", err))
	}

	// Create the docker network
	netCreateResponse, err := docker.NetworkCreate(context.Background(), internal_test.ProjectName+"_net", network.CreateOptions{
		Driver: "bridge",
		Scope:  "local",
		IPAM: &network.IPAM{
			Driver: "default",
			Config: []network.IPAMConfig{}, // Use an autogenerated IPAM config
		},
		Internal:   true,
		Attachable: false,
		Ingress:    false,
		ConfigOnly: false,
	})
	if err != nil {
		fail(fmt.Errorf("error creating network: %w", err))
	}
	if netCreateResponse.Warning != "" {
		fmt.Printf("warning creating network: %s\n", netCreateResponse.Warning)
	}

	// Create the adapters via the Docker CLI since it does stuff like pulling / tagging the image
	runCmd := fmt.Sprintf(
		"docker run --rm -d -e HD_ADAPTER_MODE=global --name %s %s",
		internal_test.GlobalAdapterContainerName,
		internal_test.AdapterTag,
	)
	fmt.Printf("!!runCmd: %v\n", runCmd)
	_, err = command.ReadOutput(runCmd)
	if err != nil {
		fail(fmt.Errorf("error running global adapter container: %w", err))
	}
	runCmd = fmt.Sprintf(
		"docker run --rm -d -e HD_ADAPTER_MODE=project -e HD_PROJECT_NAME=%s -e HD_CONFIG_DIR=%s -e HD_LOG_DIR=%s -e HD_KEY_FILE=%s -v %s:%s -v %s:%s -v %s:%s --network %s_net --name %s %s",
		internal_test.ProjectName,
		internal_test.CfgDir,
		internal_test.LogDir,
		internal_test.KeyPath,
		internal_test.CfgDir,
		internal_test.CfgDir,
		internal_test.LogDir,
		internal_test.LogDir,
		internal_test.KeyPath,
		internal_test.KeyPath,
		internal_test.ProjectName,
		internal_test.ProjectAdapterContainerName,
		internal_test.AdapterTag,
	)
	_, err = command.ReadOutput(runCmd)
	if err != nil {
		fail(fmt.Errorf("error running project adapter container: %w", err))
	}
}

// Delete all of the config files from disk
func deleteConfigs() error {
	info, err := os.ReadDir(internal_test.CfgDir)
	if err != nil {
		return fmt.Errorf("error enumerating config directory: %w", err)
	}
	for _, entry := range info {
		err = os.Remove(filepath.Join(internal_test.CfgDir, entry.Name()))
		if err != nil {
			return fmt.Errorf("error removing config file [%s]: %w", entry.Name(), err)
		}
	}
	return nil
}

// Clean up the test environment
func cleanup() {
	// Stop the adapter container
	if docker != nil {
		timeout := 0
		_ = docker.ContainerStop(context.Background(), internal_test.GlobalAdapterContainerName, container.StopOptions{Timeout: &timeout})
		_ = docker.ContainerStop(context.Background(), internal_test.ProjectAdapterContainerName, container.StopOptions{Timeout: &timeout})
		_ = docker.ContainerRemove(context.Background(), internal_test.GlobalAdapterContainerName, container.RemoveOptions{Force: true})
		_ = docker.ContainerRemove(context.Background(), internal_test.ProjectAdapterContainerName, container.RemoveOptions{Force: true})
		_ = docker.NetworkRemove(context.Background(), internal_test.ProjectName+"_net")
	}

	// Remove the temp key file
	_ = os.Remove(internal_test.KeyPath)
}

// Clean up and exit with a failure
func fail(err error) {
	cleanup()
	fmt.Fprint(os.Stderr, err.Error())
	os.Exit(1)
}
